name: Generate ASCII Artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Execute shell scripts
              run: ./bash.sh