name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "my first github action job"
            
            - name: Checkout code
              uses: actions/checkout@v4

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md
               