name: Exploring Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: Honey123
    Image_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKERUSERNAME/$IMAGENAME:latest
            
            - name: Docker login
              env:
                  DOCKER_PASSWORD: dockerpassword
              run: echo docker login --username=$DOCKERUSERNAME --password=$DOCKER_PASSWORD
            
            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKERUSERNAME/$IMAGENAME:latest
             

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8080:8080 $CONTAINER_REGISTRY/$DOCKERUSERNAME/$IMAGENAME:latest
              